[workspace]
members = [
    "crates/*",
    "examples/*",
]
resolver = "2"

[profile.release]
opt-level = 3

[workspace.package]
version = "0.1.2"
authors = ["https://github.com/polarismesh"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Lightweight Rust SDK used as Proxyless Service Governance."
homepage = "https://github.com/polarismesh/polaris-rust"
repository = "https://github.com/polarismesh/polaris-rust.git"
readme = "README.md"
keywords = ["polaris", "solution", "governance", "server", "proxyless"]
categories = ["config", "asynchronous", "development-tools"]

[workspace.dependencies]
base64 = "0.21"
bytes = "1"
bcrypt = "0.14"
hyper = "0.14"
hyper-timeout = "0.4"
hmac = "0.12"
hex = "0.4"

polaris-config = { path = "./crates/config" }
polaris-core = { path = "./crates/core" }
polaris-ratelimit = { path = "crates/ratelimit" }
polaris-registry = { path = "./crates/registry" }
polaris-router = { path = "./crates/router" }
polaris-specification = "0.1.1"

rand = "0.8"
rcgen = "0.10"
regex = "1"
tracing = "0.1"
tracing-test = "0.2.1"