[workspace]
members = [
    "crates/*",
    "examples/*",
]
resolver = "2"

[profile.release]
opt-level = 3

[workspace.package]
version = "0.1.3"
authors = ["https://github.com/polarismesh"]
edition = "2021"
rust-version = "1.63"
license = "MIT OR Apache-2.0"
description = "Lightweight Rust SDK used as Proxyless Service Governance."
homepage = "https://polarismesh.cn"
repository = "https://github.com/polarismesh/polaris-rust.git"
documentation = "https://docs.rs/polaris-rust/"
readme = "./README.md"
keywords = ["polaris", "solution", "governance", "server", "proxyless"]
categories = ["config", "asynchronous", "development-tools"]

[workspace.dependencies]
base64 = "0.21"
bytes = "1"
bcrypt = "0.15.0"
encoding_rs = "0.8"
form_urlencoded = "1"
headers = "0.3"
http = "0.2"
hyper = "1.0.1"
hyper-timeout = "0.4"
hmac = "0.12"
hex = "0.4"
log = "0.4"

openssl = "0.10"
opentelemetry-http = { version = "0.10", default-features = false }
opentelemetry-semantic-conventions = { version = "0.13", default-features = false }
opentelemetry-prometheus = { version = "0.14", default-features = false }
opentelemetry = { version = "0.21", default-features = false }

polaris-circuitbreak = { path = "./crates/circuitbreak", version = "0.1.3" }
polaris-config = { path = "./crates/config", version = "0.1.3" }
polaris-core = { path = "./crates/core", version = "0.1.3" }
polaris-discovery = { path = "./crates/discovery", version = "0.1.3" }
polaris-loadbalance = { path = "./crates/loadbalance", version = "0.1.3" }
polaris-middleware = { path = "./crates/middleware", version = "0.1.3" }
polaris-observability = { path = "./crates/observability", version = "0.1.3" }
polaris-ratelimit = { path = "./crates/ratelimit", version = "0.1.3" }
polaris-registry = { path = "./crates/registry", version = "0.1.3" }
polaris-router = { path = "./crates/router", version = "0.1.3" }

polaris-specification = "1.4.1"

quinn = { version = "0.10", default-features = false }
quote = "1"
rand = "0.8"
rcgen = "0.11"
regex = "1"
reqwest = { version = "0.11", default-features = false }
ring = "0.17"
rust_decimal = "1"
rustls = "0.21"
rustls-pemfile = "1"

serde = "1"
serde_json = "1"
serde-xml-rs = "0.6"
serde_urlencoded = "0.7"
serde_yaml = "0.9"
sha2 = "0.10"
tokio = "1"
tokio-native-tls = "0.3"
tokio-rustls = "0.24.0"
tokio-openssl = "0.6"
tokio-stream = { version = "0.1", default-features = false }
tokio-util = "0.7"
tokio-tungstenite = { version = "0.20.1", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-test = "0.2.1"
url = "2"
x509-parser = "0.15.0"

# Compress
brotli = { version = "3.3", default-features = false }
flate2 = { version = "1.0", default-features = false }
zstd = { version = "0.13", default-features = false }