[workspace]
members = [
    "crates/*",
    "examples/*",
]
resolver = "2"

[profile.release]
opt-level = 3

[workspace.package]
version = "0.1.3"
authors = ["https://github.com/polarismesh"]
edition = "2021"
rust-version = "1.63"
license = "MIT OR Apache-2.0"
description = "Lightweight Rust SDK used as Proxyless Service Governance."
homepage = "https://polarismesh.cn"
repository = "https://github.com/polarismesh/polaris-rust.git"
documentation = "https://docs.rs/polaris-rust/"
readme = "./README.md"
keywords = ["polaris", "solution", "governance", "server", "proxyless"]
categories = ["config", "asynchronous", "development-tools"]

[workspace.dependencies]
base64 = "0.21"
bytes = "1"
bcrypt = "0.14"
encoding_rs = "0.8"
form_urlencoded = "1"
headers = "0.3"
http = "0.2"
hyper = "0.14"
hyper-timeout = "0.4"
hmac = "0.12"
hex = "0.4"

polaris-config = { path = "./crates/config", version = "0.1.3" }
polaris-core = { path = "./crates/core", version = "0.1.3" }
polaris-ratelimit = { path = "./crates/ratelimit", version = "0.1.3" }
polaris-registry = { path = "./crates/registry", version = "0.1.3" }
polaris-router = { path = "./crates/router", version = "0.1.3" }
polaris-specification = "0.1.1"


rand = "0.8"
rcgen = "0.10"
regex = "1"
rustls = "0.20"
serde = "1"
serde_json = "1"
tokio = "1"
tokio-native-tls = "0.3"
tokio-rustls = "0.23"
tokio-openssl = "0.6"
tokio-stream = { version = "0.1", default-features = false }
tokio-util = "0.7"
tokio-tungstenite = { version = "0.18", default-features = false }
tracing = "0.1"
tracing-test = "0.2.1"
url = "2"
x509-parser = "0.15.0"